eventpoll/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles import views


urlpatterns = [
    url(r'^', include('polling.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

polling/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from .views import IndexView
from .api import PollingViewSet, ActivePollingManageSet, EventNameViewSet, EventViewSet
from .api import ResulViewSet, ParticipantViewSet


app_name = 'polling'

router = routers.SimpleRouter()
router.register(r'polling', PollingViewSet, base_name='polling')
router.register(r'active-polling', ActivePollingManageSet, base_name='active-polling')
router.register(r'event-name', EventNameViewSet, base_name='event-name')
router.register(r'polling/(?P<polling_id>[^/.]+)/participants', ParticipantViewSet, base_name='participants')
router.register(r'polling/(?P<polling_id>[^/.]+)/events', EventViewSet, base_name='events')
router.register(r'polling/(?P<polling_id>[^/.]+)/results', ResulViewSet, base_name='results')


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^api/', include(router.urls, namespace='api')),
]

polling/models.py
import logging

from datetime import timedelta
from functools import wraps

import pytz
from django.core.exceptions import ValidationError
from django.conf import settings
from django.db import models
from django.db.models import Count, Max
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django_extensions.db.models import TimeStampedModel
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.utils import IntegrityError
from django.contrib.auth import get_user_model

from .exceptions import PollingOnlyOneActiveValidationError, PollingIsNotActiveValidationError
from .exceptions import PollingCanNotChangeStateValidationError


log = logging.getLogger(__name__)


USER_MODEL = getattr(settings, 'AUTH_USER_MODEL')


def must_be_active(func):
    @wraps(func)
    def wrapper(self):
        if not self.active:
            raise PollingIsNotActiveValidationError()
        func(self)
    return wrapper


def get_timezone(value):
    try:
        return pytz.timezone(value)
    except pytz.UnknownTimeZoneError as e:
        raise e


class PollingManager(models.Manager):
    def get_active_polling(self):
        try:
            p = self.get(actual=0)
            p.check_state()
            if p.active:
                return p
            else:
                return None
        except Polling.DoesNotExist:
            return None


class Polling(TimeStampedModel):
    """

    """
    FIRST_PHASE = "FIRST"
    SECOND_PHASE = "SECOND"
    FINISHED = "FINISHED"
    TERMINATED = "TERMINATED"

    POLLING_STATE_CHOICES = (
        (FIRST_PHASE, _('The polling is in the first phase.')),
        (SECOND_PHASE, _('The polling is in the second phase.')),
        (FINISHED, _('The polling is finished.')),
        (TERMINATED, _('The polling was terminated.')),
    )

    user = models.ForeignKey(USER_MODEL,
                             related_name='pollings',
                             verbose_name=_('Polling user'),
                             on_delete=models.PROTECT)
    name = models.CharField(verbose_name=_('Name'),
                            max_length=100,
                            default='',
                            blank=True)
    description = models.TextField(verbose_name=_('Description'),
                                   default='',
                                   blank=True)
    first_phase_duration = models.PositiveSmallIntegerField(verbose_name=_('First phase duration (min)'),
                                                            validators=[MinValueValidator(1)])
    second_phase_duration = models.PositiveSmallIntegerField(verbose_name=_('Second phase duration (min)'),
                                                             validators=[MinValueValidator(1)])
    start_time = models.DateTimeField(verbose_name=_('Starts at time'))
    first_phase_finish_time = models.DateTimeField(verbose_name=_('The first phase has to be finished at'))
    finish_time = models.DateTimeField(verbose_name=_('The polling has to be finished at'))
    terminated_at = models.DateTimeField(verbose_name=_('The time of the polling termination'),
                                         default=None,
                                         blank=True,
                                         null=True)
    original_hour = models.PositiveSmallIntegerField(verbose_name=_('Polling interval between original hour and 23'),
                                                     validators=[MaxValueValidator(23)],
                                                     default=0)
    original_timezone = models.CharField(verbose_name=_('Original timezone'),
                                         max_length=63,
                                         default='',
                                         blank=True)
    # The polling is active when polling.actual == 0 --
    actual = models.BigIntegerField(verbose_name=_('Actuality'),
                                    unique=True)
    state = models.CharField(verbose_name=_('The state of the polling'),
                             max_length=10,
                             choices=POLLING_STATE_CHOICES,
                             default=FIRST_PHASE)

    objects = PollingManager()

    def __str__(self):
        return "{} {}".format(self.id, self.name)

    @property
    def active(self):
        return self.actual == 0

    def get_voted_users(self):
        return get_user_model().objects.filter(votes__event__polling=self).distinct()

    def is_participant(self, user):
        return self.participants.filter(user=user).exists()

    @property
    def voted_users_counter(self):
        return get_user_model().objects.filter(votes__event__polling=self).distinct().count()

    def clean(self):
        if self.active:
            raise ValidationError(message=_('Can not modify the active polling'))

    def save(self, *args, **kwargs):
        if not self.pk:
            self._set_phase_times()
            self.state = self.FIRST_PHASE
            self.actual = 0

        try:
            super(Polling, self).save(*args, **kwargs)
        except IntegrityError as exc:
            raise PollingOnlyOneActiveValidationError()

    def _clear_results(self):
        for event in self.events.all():
            event.votes.all().delete()

        self.participants.all().delete()
        self.results.all().delete()

    def _set_phase_times(self):
        self.start_time = timezone.now()
        self.terminated_at = None
        self.first_phase_finish_time = self.start_time + timedelta(minutes=self.first_phase_duration)
        self.finish_time = self.first_phase_finish_time + timedelta(minutes=self.second_phase_duration)

    def _deactivate(self):
        self.actual = self.pk

    def _get_results(self):
        annotated_events = self.events.annotate(num_votes=Count('votes'))
        max_events = annotated_events.aggregate(Max('num_votes'))
        result_events = annotated_events.filter(num_votes=max_events['num_votes__max'])
        Result.objects.bulk_create([Result(polling=self, event=e) for e in result_events])

    def _get_list_of_participants_from_results(self):
        voters = self.user.__class__.objects.filter(votes__event__results__polling=self)
        for voter in set(voters):
            Participant.objects.create(polling=self, user=voter)

    @must_be_active
    def restart(self):
        self._clear_results()
        self._set_phase_times()
        self.state = self.FIRST_PHASE
        self.save()
        return self

    @must_be_active
    def terminate(self):
        self._deactivate()
        self.state = self.TERMINATED
        self.terminated_at = timezone.now()
        self.save()
        return self

    def check_state(self):
        """Return True if the polling state corresponds with start and finish time points.
        Otherwise correct state and return False

        :return: bool
        """

        if not self.active:
            if self.state == self.FINISHED or self.state == self.TERMINATED:
                return True
            else:
                # incorrect state. set terminated
                self.state = self.TERMINATED
                self.terminated_at = timezone.now()
                self.save()
                return False

        # The polling is active,
        # If all time points are not set then terminate
        if not self.start_time or not self.first_phase_finish_time or not self.finish_time:
            self.terminate()
            return False

        # Compare state, time points and current time
        now = timezone.now()
        if self.state == self.SECOND_PHASE:
            # normal second phase
            if self.first_phase_finish_time <= now < self.finish_time:
                return True

            # The time of polling is over but celery task is missed.
            if now > self.finish_time:
                self.finish_polling()
                return False

        if self.state == self.FIRST_PHASE:
            # normal first phase
            if self.start_time <= now < self.first_phase_finish_time:
                return True

            # The time of the first phase is over but celery task is missed
            if self.first_phase_finish_time < now <= self.finish_time:
                self.finish_first_phase()
                return False

        #  Other states of active polling are incorrect. So we terminate polling
        self.terminate()
        return False

    @must_be_active
    def finish_first_phase(self):
        if self.state == self.FIRST_PHASE:
            self._get_results()
            self._get_list_of_participants_from_results()
            self.state = self.SECOND_PHASE
            self.save()
            return self

        raise PollingCanNotChangeStateValidationError()

    @must_be_active
    def finish_polling(self):
        log.debug('Model finish polling.  self.state == {}'.format(self.state))
        if self.state == self.SECOND_PHASE:
            self._deactivate()
            self.state = self.FINISHED
            self.save()
            return self

        raise PollingCanNotChangeStateValidationError()


class Event(models.Model):
    polling = models.ForeignKey('Polling',
                                related_name='events',
                                verbose_name=_('Polling'))
    hour = models.PositiveSmallIntegerField(verbose_name=_('Hour'),
                                            validators=[MinValueValidator(0), MaxValueValidator(23)])
    event_name = models.ForeignKey('EventName',
                                   verbose_name=_('Event name'),
                                   on_delete=models.PROTECT)

    def clean(self):
        # hour should not be less than original_hour
        if not self.polling.active:
            raise ValidationError({_('You can add event to inactive polling!')})

        if self.polling.state != Polling.FIRST_PHASE:

polling/controller.py
"""
Application logic controller.


"""

from channels.generic.websockets import WebsocketMultiplexer
from django.db.models import signals
from django.dispatch import receiver

from .utils import Singleton
from .settings import POLLING_CHANNEL_GROUP, POLLING_STREAM
from .tasks import set_finish_first_phase, set_finish_polling
from .models import Polling, Event, EventName, Vote, Participant
from .serializers import PollingSerializer, EventSerializer, EventNameSerializer, ParticipantSerializer


class Controller(metaclass=Singleton):
    """
    Application logic controller.

    """
    polling_channel_group = POLLING_CHANNEL_GROUP
    polling_sream = POLLING_STREAM

    @classmethod
    def user_channel_group(cls, user):
        """
        Returns name of channel group for user

        We use user.id to identify user channel.

        :param user: object User
        :return: str
        """

        if hasattr(user, 'id'):
            return "user_{}.channel.group".format(user.id)
        else:
            return "user_{}.channel.group".format(repr(user))

    def websocket_receive(self, user, content, **kwargs):
        pass

    @classmethod
    def send_message_to_all(cls, payload):
        WebsocketMultiplexer.group_send(name=POLLING_CHANNEL_GROUP, stream=POLLING_STREAM, payload=payload)

    @classmethod
    def send_message_to_user(cls, user, message):
        pass

    @classmethod
    def _send_action(cls, action, serializer, instance, extra_query_set=None):
        """ Send to channels processed actions

        :param action:
        :param serializer:
        :param instance:
        :param extra_query_set:
        :return:
        """
        payload = {'action': action,
                   'data': serializer(instance).data}
        if extra_query_set:
            payload['extra'] = serializer(extra_query_set, many=True).data

        Controller.send_message_to_all(payload)

    def send_start_polling(self, instance, **kwargs):
        self._send_action('start_polling', PollingSerializer, instance)

    def send_change_polling(self, instance, **kwargs):
        self._send_action('change_polling', PollingSerializer, instance)

    def send_add_event(self, instance, **kwargs):
        self._send_action('add_event', EventSerializer, instance, instance.polling.events)

    def send_change_event(self, instance, **kwargs):
        self._send_action('change_event', EventSerializer, instance, instance.polling.events)

    def send_remove_event(self, instance, **kwargs):
        self._send_action('remove_event', EventSerializer, instance, instance.polling.events)

    def send_add_event_name(self, instance, **kwargs):
        self._send_action('add_event_name', EventNameSerializer, instance, EventName.objects.all())

    def send_remove_event_name(self, instance, **kwargs):
        self._send_action('remove_event_name', EventNameSerializer, instance, EventName.objects.all())

    def send_add_participant(self, instance, **kwargs):
        self._send_action('add_participant', ParticipantSerializer, instance, instance.polling.participants)

    def send_remove_participant(self, instance, **kwargs):
        self._send_action('remove_participant', ParticipantSerializer, instance, instance.polling.participants)

    def send_voted_users_counter(self, voted_users_counter, **kwargs):
        payload = {'action': 'change_voted_users',
                   'data': {'counter': voted_users_counter}}
        self.send_message_to_all(payload)


polling_controller = Controller()


@receiver(signals.post_save, sender=Polling)
def polling_post_save(sender, instance, created, raw, using, update_fields, **kwargs):
    # The polling is just started. Put celery tasks
    if created:
        polling_controller.send_change_polling(instance)
        # set task to finish the first phase
        set_finish_first_phase.apply_async(
            (
                instance.pk,
                instance.first_phase_finish_time,
                polling_controller.polling_channel_group,
                polling_controller.polling_sream,
                {'action': 'finish_first_phase',
                 'data': PollingSerializer(instance).data}
            ),
            eta=instance.first_phase_finish_time
        )
        # set task to finish the polling
        set_finish_polling.apply_async(
            (
                instance.pk,
                instance.finish_time,
                polling_controller.polling_channel_group,
                polling_controller.polling_sream,
                {'action': 'finish_polling',
                 'data': PollingSerializer(instance).data}
            ),
            eta=instance.finish_time
        )
    else:
        polling_controller.send_change_polling(instance)


@receiver(signals.post_save, sender=Event)
def event_post_save(sender, instance, created, raw, using, update_fields, **kwargs):
    if created:
        polling_controller.send_add_event(instance)
    else:
        polling_controller.send_change_event(instance)


@receiver(signals.post_delete, sender=Event)
def event_post_delete(sender, instance, using, **kwargs):
    polling_controller.send_remove_event(instance)


@receiver(signals.post_save, sender=EventName)
def event_name_post_save(sender, instance, created, raw, using, update_fields, **kwargs):
    if created:
        polling_controller.send_add_event_name(instance)


@receiver(signals.post_delete, sender=EventName)
def event_name_post_delete(sender, instance, using, **kwargs):
    polling_controller.send_remove_event_name(instance)


@receiver(signals.post_save, sender=Participant)
def participant_post_save(sender, instance, created, raw, using, update_fields, **kwargs):
    if created:
        polling_controller.send_add_participant(instance)


@receiver(signals.post_delete, sender=Participant)
def participant_post_delete(sender, instance, using, **kwargs):
    polling_controller.send_remove_participant(instance)


@receiver(signals.post_save, sender=Vote)
def participant_post_save(sender, instance, created, raw, using, update_fields, **kwargs):
    if created:
        polling_controller.send_voted_users_counter(instance.event.polling.voted_users_counter)


@receiver(signals.post_delete, sender=Vote)
def participant_post_delete(sender, instance, using, **kwargs):
    polling_controller.send_voted_users_counter(instance.event.polling.voted_users_counter)

polling/templates/polling/index.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'css/polling/polling.css' %}">
{% endblock %}

{% block scripts %}
{{ block.super }}
<script src="{% static 'js/select2.min.js' %}"></script>
<script src="{% static 'channels/js/websocketbridge.js' %}"></script>
{% endblock%}

{% block content %}
{% verbatim %}
<div class="container-fluid">
<div id="eventpoll" v-cloak>
    <template v-if=" !activePolling ">
        <button id="show-new-polling" @click="showNewPolling = true" class="btn btn-primary btn-lg">
            Создать голосование
        </button>
        <new-polling v-if="showNewPolling" @close="showNewPolling = false" v-on:newpolling="createPolling">
        </new-polling>
    </template>
    <template v-else>
        <div>
            <h4>{{ activePolling.name }}</h4>
            <p>{{ activePolling.description }} </p>
            <p>{{ activePolling.first_phase_duration }}</p>
            <p>{{ activePolling.second_phase_duration }}</p>
            <p>{{ startTime }}</p>
        </div>
        <div>
            <button class="btn btn-primary" v-on:click="restartPolling" title="Restart the polling">Начать голосование заново!</button>
            <button class="btn btn-primary" v-on:click="terminatePolling" title="Terminate the polling">Аварийно завершить голосование!</button>
        </div>
        <template v-if=" isFirstPhase ">
            <div>
                <div class="vote-counter">
                    <h4> Проголосовало пользователей </h4>
                    <p class="digit">{{ votedUsersCounter }}</p>
                </div>
                <countdown-timer v-bind="firstPhaseTimer" class="col-sm-4">
                </countdown-timer>
                <countdown-timer v-bind="finishTimer" class="col-sm-4">
                </countdown-timer>
            </div>
            <event-list>
            </event-list>
        </template>
        <template v-else>
            <!--second phase-->
            <countdown-timer v-bind="finishTimer">
            </countdown-timer>
            <vote-chart>
            </vote-chart>
            <polling-result>
            </polling-result>
            <participants>
            </participants>
        </template>
    </template>
    <polling-list>
    </polling-list>
</div>

{% endverbatim %}
{% endblock %}

{% block body_script %}
{{ block.super }}

{% verbatim %}
<script type="text/x-template" id="new-polling">
    <transition name="new-polling">
        <div class="modal-mask">
            <div class="modal-wrapper">
                <div class="modal-container">
                    <div class="modal-header">
                         <h3>Новое голосование</h3>
                    </div>
                    <div class="modal-body">
                        <form class="form-horizontal" v-on:submit.prevent>
                            <fieldset>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="id_name">Название</label>
                                    <div class="col-sm-10">
                                        <input v-model="name" id="id_name" class="form-control" name="name" type="text">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="id_description">Описание</label>
                                    <div class="col-sm-10">
                                        <textarea v-model="description" class="form-control" name="description" id="id_description"></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-5 control-label" for="id_first_phase_duration">Продолжительность первой фазы (минут)</label>
                                    <div class="col-sm-7">
                                        <input v-model="firstPhaseDuration" class="form-control" name="first_phase_duration" type="number" min="1" value="1" id="id_first_phase_duration">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-5 control-label" for="id_second_phase_duration">Продолжительность второй фазы (минут)</label>
                                    <div class="col-sm-7">
                                        <input v-model="secondPhaseDuration" class="form-control" name="second_phase_duration" type="number" min="1" value="1" id="id_second_phase_duration">
                                    </div>
                                </div>
                                <div class="form-actions">
                                    <button class="btn btn-primary" v-on:click="createNewPolling" title="Create a polling">Создать голосование</button>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button class="modal-default-button" @click="$emit('close')">
                            Закрыть
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </transition>
</script>

<script type="text/x-template" id="polling-list">
</script>

<script type="text/x-template" id="countdown-timer">
    <div class="countdown-timer">
        <h4> {{ timerTitle }} </h4>
        <ul>
            <li>
                <p class="digit">{{ hours | twoDigits }}</p>
                <p class="text">часов</p>
            </li>
            <li>
                <p class="digit">{{ minutes | twoDigits }}</p>
                <p class="text">минут</p>
            </li>
            <li>
                <p class="digit">{{ seconds | twoDigits }}</p>
                <p class="text">секунд</p>
            </li>
        </ul>
    </div>
</script>

<script type="text/x-template" id="event-list">
    <div class="event-list">


    </div>
</script>

<script type="text/x-template" id="vote-chart">
</script>

<script type="text/x-template" id="participants">

</script>

    {% endverbatim %}

<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<!--<script src="{% static 'js/vue.js' %}"></script>-->
<!--<script src="{% static 'js/axios.min.js' %}"></script>-->
<script src="{% static 'js/js.cookie.js' %}"></script>
<script src="{% static 'js/polling/polling.js' %}"></script>

{% endblock %}